// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/add-bank-account-wio": {
    params: {};
  };
  "/add-bank-account-operator": {
    params: {};
  };
  "/.well-known/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/add-bank-account-wio" | "/add-bank-account-operator" | "/.well-known/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/add-bank-account-wio.tsx": {
    id: "routes/add-bank-account-wio";
    page: "/add-bank-account-wio";
  };
  "routes/add-bank-account-operator.tsx": {
    id: "routes/add-bank-account-operator";
    page: "/add-bank-account-operator";
  };
  "routes/well-known.tsx": {
    id: "routes/well-known";
    page: "/.well-known/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/add-bank-account-wio": typeof import("./app/routes/add-bank-account-wio.tsx");
  "routes/add-bank-account-operator": typeof import("./app/routes/add-bank-account-operator.tsx");
  "routes/well-known": typeof import("./app/routes/well-known.tsx");
};